stages:
    - build
    - release

systolic:
    stage: build
    except:
      - schedules
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
      - source /tools/setup.sh
      - ./manager.sh update_deps
      - make generate_verilog TOP_MODULE=mksystolic_top TOP_FILE=src/systolic_template.bsv VERILOGDIR=mksystolic_top TOP_DIR=./
      - make clean
      - make release REL_DIR=/scratch/gitlab-builds/releases/systolic
      - ./manager.sh nuke
    only:
        - master
    tags:
        - shakti-runner

release:
    stage: release
    script:
        - python3 /scratch/version-extract.py
    only:
        refs:
            - master
    tags:
        - shakti-runner
    except:
      - schedules
