### Makefile for the Systolic project
### Generated by Bluespec Workstation on Sat May 26 15:42:56 IST 2018
AXI4:=./../../../../repos/c-class/src/uncore/axi4
default: full_clean compile link simulate

.PHONY: compile
compile:
	@echo Compiling...
	bsc -u -verilog -elab -vdir verilog -bdir inter -info-dir inter -keep-fires -p .:%/Prelude:%/Libraries:%/Libraries/BlueNoC:$(AXI4) -g mksystolic3  systolic.bsv 
	@echo Compilation finished

.PHONY: link
link:
	@echo Linking...
	bsc -e mksystolic3 -verilog -o ./out -vdir verilog  -vsim cvc  -keep-fires verilog/mksystolic3.v
	@echo Linking finished

.PHONY: simulate
simulate:
	@echo Simulation...
	./out 
	@echo Simulation finished

.PHONY: clean
clean:
	exec rm -f inter/intMul.bo inter/Cur_Cycle.bo inter/Semi_FIFOF.bo inter/systolic.bo inter/AXI4_Fabric.bo inter/AXI4_Types.bo
	exec rm -f inter/mksystolic3.ba inter/mkintMul.ba

.PHONY: full_clean
full_clean:
	rm -f inter/intMul.bo inter/Cur_Cycle.bo inter/Semi_FIFOF.bo inter/systolic.bo inter/AXI4_Fabric.bo inter/AXI4_Types.bo
	rm -f inter/mksystolic3.ba inter/mkintMul.ba
	rm -f verilog/mksystolic3.v
	rm -f verilog/mkintMul.v
